<?php
/**
 * Sales And Orders Feed Tool
 * Copyright © 2019 S&O LLC. All rights reserved.
 * See LICENSE.txt for license details.
 */

/**
 * @var \SalesAndOrders\FeedTool\Block\Adminhtml\Page\View $block
 */

$viewData = $block->getIframeLinkData();
?>

<script type="text/javascript">
    require([
        'mage/url'
    ], function(url) {
        return url.setBaseUrl('<?=$block->escapeUrl($block->getAdminBaseUrl());?>');
    });
</script>

<?php if ($viewData['content']): ?>
    <div class="header-view-block">
        <!--<button id="deactivate_integration">Deactivate</button>
        <button id="delete_integration">Delete</button>-->
    </div>
    <iframe 
        id="iFrame" src="<?=$block->escapeUrl($viewData['url']);?>" style="width:100%; height:800px" frameborder="0">
    </iframe>
<?php else: ?>
    <div class="header-view-block">
        <img src="<?=$block->escapeUrl($block->getViewFileUrl('SalesAndOrders_FeedTool::images/logo.png'));?>">
        <button class="activate" id="popup-modal">Install</button>
        <img 
        class="loader" 
        src="<?=$block->escapeUrl($block->getViewFileUrl('SalesAndOrders_FeedTool::images/load.gif')); ?>">
<!--        <button id="add_integration">Add</button>-->
<!--        <button id="deactivate_integration">Deactivate</button>-->
<!--        <button id="delete_integration">Delete</button>-->
    </div>
    <div class="content-view-block">
        <div class="content-view-block-left">
            <h3>Sales and Orders requires:</h3>
            <ul>
                <li>
                    <p>View basic store information</p>
                </li>
                <li>
                    <p>View general store information</p>
                </li>
                <li>
                    <p>View and modify products</p>
                </li>
                <li>
                    <p>View Customers information</p>
                </li>
                <li>
                    <p>View and create orders</p>
                </li>
            </ul>
        </div>
        <div class="content-view-block-center">
            <ul>

            </ul>
        </div>
    </div>
<?php endif ?>
